# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

[battery]
disabled = true

[character] # The name of the module we are configuring is "character"
success_symbol = "[â¯](bold green)"

[direnv]
format = '[$symbol$allowed]($style) '
disabled = false
allowed_msg = "âœ“"
not_allowed_msg = "ğ„‚"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[git_branch]
style = "bold yellow"

[terraform]
format = '[TF $version]($style) '

[git_state]
disabled = false

[kubernetes]
disabled = false
